### ISSUE TITLE
Optionally disable adding ImagePullSecrets to ServiceAccounts

### ISSUE THREAD

**Issue by LuciferInLove** [openshift/openshift-controller-manager#255]
Hello.
I created an OpenShift cluster on AWS using `rosa`. An internal registry has been installed. `openshift-controller-manager` adds ImagePullSecrets to each ServiceAccount in all namespaces.

Need a way to optionally disable this for a specific namespace/serviceAccount. For example, an annotation.

**Comment by erikgb** [comment]
/remove-lifecycle rotten

Maybe issues should be disabled on this project if no maintainers look at them? 🤔
